### ISSUE TITLE
Possible to input wildcards?

### ISSUE THREAD

**Issue by pa-0** [ghfetch/ghfetch#4]
For example, is it possible to input **`<username> *`** to get a list of all repos under a user account?

**Comment by nullgaro** [comment]
I'm looking into it, I like the idea

**Comment by nullgaro** [comment]
Sorry for the delay @pa-0.

As of 1.9, you can get the repositories of any user/organisation by typing "/*" at the end of the username.

I'll leave some examples below:
```
ghfetch nullgaro/*
ghfetch ghfetch/*
ghfetch pa-0/*
```
